### PR TITLE
Add riscv64gc target

### PR DESCRIPTION
**Pull request by Vixea**
a little personal project of mine requires support for RISC-V

### CODE REVIEW

**Comment by Vixea** [comment]
one thing that needs addressing is the rest of the ci

**Comment by Vixea** [comment]
just decided to skip the ci maybe @katyo can try CI is not my forte.

**Comment by Drakulix** [comment]
Can you please run the generated files through `cargo fmt`

**Comment by Vixea** [comment]
yep, I noice no changes

**Comment by Drakulix** [comment]
> yep, I noiced no changes when running `cargo fmt`

Well every other platform is formatted, please figure this out, this makes it completely impossible to inspect the files for basic functionality.

**Comment by Vixea** [comment]
done manually with rustfmt. idk but it seems like cargo fmt broke for me, idk

**Comment by Vixea** [comment]
and got drm-rs done while I was at this, review whenever you want

**Review by Drakulix — APPROVED** [review]
LGTM

**Pull request merged**
