### PR TITLE
Bump version numbers

### LINKED ISSUE #29: Release v0.6.0
Because the last release (0.5.0) on crate.io was over a year ago, how about release 0.6.0.

### PR DESCRIPTION
**Pull request by katyo**
Closes #29

@Drakulix,
Could you set `CRATES_TOKEN` for this repo and push v0.6.0 tag?

### CODE REVIEW

**Comment by Drakulix** [comment]
Thanks for the reminder.

It seems the cross-compilation tests are failing due to some package problems. Any idea whats going on?

**Comment by katyo** [comment]
@Drakulix Seems gh installed gcc-11 backport to ubuntu-20.04.
Unfortunately I don't found this packport in official repositories.
I will try to downgrade gcc to 10 to solve this issue.

**Comment by katyo** [comment]
I tried to use containers but unfortunately the job stuck.
It seems this isn't my mistake. Sometimes this occurs with GH Actions.

**Comment by katyo** [comment]
@Drakulix Can you review and merge this PR?

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
